trigger:
  branches:
    include:
      - main
      - testingbranch

pr:
  branches:
    include:
      - main
      # optionally include testingbranch if you want PR validation into testingbranch

schedules:
- cron: "30 0 * * *"
  displayName: "Daily build at 6 AM IST"
  branches:
    include:
    - main
    - testingbranch
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
# ✅ Update apt-get
- script: sudo apt-get update
  displayName: 'Update apt-get'

# ✅ Install latest Google Chrome
- script: |
    wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
    sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    sudo apt-get update
    sudo apt-get install -y google-chrome-stable
    google-chrome --version
  displayName: 'Install Google Chrome'

# ✅ Install matching ChromeDriver dynamically
- script: |
    CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1 | cut -d. -f1)
    echo "Detected Chrome major version: $CHROME_VERSION"

    CHROMEDRIVER_VERSION=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_VERSION")
    echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"

    wget https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip
    unzip chromedriver-linux64.zip
    sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
    chromedriver --version
  displayName: 'Install matching ChromeDriver'

# ✅ Check Java version
- script: java -version
  displayName: 'Check Java Version'

# ✅ Run Maven Build + Tests (headless mode forced)
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    goals: 'clean test'
    options: '-Dheadless=true'

