trigger:
  branches:
    include:
      - main
      - testingbranch

pr:
  branches:
    include:
      - main
      # - testingbranch   # uncomment if you want PR validation into testingbranch

schedules:
- cron: "30 0 * * *"
  displayName: "Daily build at 6 AM IST"
  branches:
    include:
      - main
      - testingbranch
  always: true

pool:
  vmImage: 'ubuntu-latest'

steps:
# update package list
- script: sudo apt-get update
  displayName: 'Update apt-get'

# install required tools (wget, unzip)
- script: sudo apt-get install -y wget unzip
  displayName: 'Install wget & unzip'

# Install Google Chrome
- script: |
    sudo apt-get install -y google-chrome-stable
    google-chrome --version
  displayName: 'Install Google Chrome'

# Install matching ChromeDriver dynamically (matches Chrome major version)
- script: |
    set -e
    CHROME_VER=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1 | cut -d. -f1)
    echo "Detected Chrome major version: $CHROME_VER"

    CHROMEDRIVER_VERSION=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_VER")
    echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"

    URL="https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
    echo "Downloading from: $URL"
    wget -q "$URL" -O chromedriver-linux64.zip
    unzip -q chromedriver-linux64.zip
    sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
    sudo chmod +x /usr/local/bin/chromedriver
    /usr/local/bin/chromedriver --version
  displayName: 'Install matching ChromeDriver'

# Check Java
- script: java -version
  displayName: 'Check Java Version'

# Run Maven Build + Tests (headless mode forced for CI)
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    goals: 'clean test'
    options: '-Dheadless=true'
