trigger:
  branches:
    include:
      - main
      - testingbranch

pool:
  vmImage: ubuntu-latest

steps:
# update package list
- script: sudo apt-get update
  displayName: 'Update apt-get'

# install required tools
- script: |
    sudo apt-get install -y wget unzip
  displayName: 'Install wget & unzip'

# Install Google Chrome
- script: |
    sudo apt-get install -y google-chrome-stable
    google-chrome --version
  displayName: 'Install Google Chrome'

# Install matching ChromeDriver dynamically (matches Chrome major version)
- script: |
    CHROME_VER=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1 | cut -d. -f1)
    echo "Detected Chrome major version: $CHROME_VER"
    CHROMEDRIVER_VERSION=$(curl -sS "https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_$CHROME_VER")
    echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
    wget -q "https://storage.googleapis.com/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip"
    unzip -q chromedriver-linux64.zip
    sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
    /usr/local/bin/chromedriver --version
  displayName: 'Install matching ChromeDriver'

# Check Java
- script: java -version
  displayName: 'Check Java Version'

# Run Maven Build + Tests (force headless for CI)
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    goals: 'clean test'
    options: '-Dheadless=true'
